name: sora
description: "Sora is an open-source GUI for gallery-dl"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^10.0.1
  bloc: ^9.0.0
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  intl: 0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  oxidized: ^6.2.0
  path: ^1.9.1
  path_provider: ^2.1.5
  process_run: ^1.2.4
  slang: ^4.7.1
  slang_flutter: ^4.7.0
  string_validator: ^1.1.0
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  auto_route_generator: ^10.0.1
  build_runner: ^2.4.15
  drift_dev: ^2.26.0
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  slang_build_runner: ^4.7.0
  very_good_analysis: ^7.0.0

flutter_launcher_icons:
  linux:
    generate: true
    image_path: assets/images/sora_logo.png

flutter:

  uses-material-design: true

  assets:
    - assets/images/
